from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT.parent / "Belgium Campus.zip"

# Public project set. DBD is deliberately excluded until explicitly approved.
PROJECTS = {
    "cloud-native-student-qualifier": "CNA261 — Cloud Native / Docker",
    "windows-server-hybrid-infrastructure": "OPS261 — Windows Server / Infrastructure",
    "windows-powershell-admin-toolkit": "OPS262 — PowerShell / Automation",
    "iot-human-detection-probe": "IOT261 — Human Detection Probe",
    "iot-aquasense": "PMM261 — AquaSense",
    "information-networking": "INL261 — Information Networking",
    "enterprise-resource-planning-case-study": "ERP261 — Enterprise Resource Planning",
}

FORBIDDEN_TERMS = {
    "DBD261",
    "database-sql-server",
    "database-systems",
}

SECRET_PATTERNS = [
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"(?i)aws_secret_access_key\s*[:=]"),
    re.compile(r"(?i)(api[_-]?key|access[_-]?token|client[_-]?secret)\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{12,}"),
]

PRIVATE_MARKERS = {
    "student number",
    "student number:",
    "lecturer email",
    "private correspondence",
    "group member",
}


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    print("$", " ".join(cmd))
    return subprocess.run(cmd, cwd=ROOT, text=True, check=check)


def git_is_repo() -> bool:
    result = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.returncode == 0


def verify_source(source: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(
            f"Source archive not found: {source}. Place 'Belgium Campus.zip' beside this repository "
            "or pass --source <path>."
        )


def inspect_source(source: Path) -> dict[str, int]:
    counts = {name: 0 for name in PROJECTS}
    with zipfile.ZipFile(source) as zf:
        names = zf.namelist()
        lowered = [name.lower() for name in names]

        if any("dbd261" in name or "/dbd" in name for name in lowered):
            print("[policy] DBD material detected in source archive — it will NOT be published.")

        for project in PROJECTS:
            token = project.split("-")[0]
            if project == "cloud-native-student-qualifier":
                token = "cna261"
            elif project == "windows-server-hybrid-infrastructure":
                token = "ops261"
            elif project == "windows-powershell-admin-toolkit":
                token = "ops262"
            elif project == "iot-human-detection-probe":
                token = "iot261"
            elif project == "iot-aquasense":
                token = "pmm 261"
            elif project == "information-networking":
                token = "inl261"
            elif project == "enterprise-resource-planning-case-study":
                token = "erp261"

            counts[project] = sum(1 for name in lowered if token in name)

    return counts


def write_manifest(counts: dict[str, int]) -> None:
    lines = [
        "# Portfolio Build Manifest",
        "",
        "Generated by `python scripts/build_portfolio.py`.",
        "",
        "| Portfolio project | Academic source files detected | Public status |",
        "|---|---:|---|",
    ]
    for project, label in PROJECTS.items():
        lines.append(f"| {label} | {counts[project]} | Included |")
    lines.extend([
        "| DBD261 — Database Development | — | **Excluded by policy** |",
        "",
        "> Raw assignments, marks, student identifiers, private correspondence and group-member information are not published by the builder.",
        "",
    ])
    (ROOT / "PORTFOLIO-BUILD-MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")


def validate() -> None:
    required = [
        ROOT / "README.md",
        ROOT / "PROJECT-MAP.md",
        ROOT / "SECURITY-POSITIONING.md",
        ROOT / "SOC-LAB-ROADMAP.md",
        ROOT / "PORTFOLIO-OPERATING-RULES.md",
    ]

    for path in required:
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError(f"Missing required file: {path.relative_to(ROOT)}")

    # DBD must not exist in the current working tree.
    forbidden_hits = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = str(path.relative_to(ROOT)).lower()
        if any(term.lower() in rel for term in FORBIDDEN_TERMS):
            forbidden_hits.append(rel)
        if path.suffix.lower() in {".md", ".txt", ".py", ".yml", ".yaml", ".ps1", ".sql"}:
            text = path.read_text(encoding="utf-8", errors="ignore")
            if "DBD261" in text or "database-sql-server" in text:
                forbidden_hits.append(rel + " [content reference]")
            for marker in PRIVATE_MARKERS:
                if marker.lower() in text.lower():
                    print(f"[review] private-academic marker found in {rel}: {marker}")
            for pattern in SECRET_PATTERNS:
                if pattern.search(text):
                    raise RuntimeError(f"Possible credential pattern in {rel}")

    if forbidden_hits:
        raise RuntimeError("DBD/private database material detected: " + ", ".join(sorted(set(forbidden_hits))))

    # Project directories must exist and have a README.
    for project in PROJECTS:
        readme = ROOT / "projects" / project / "README.md"
        if not readme.exists() or readme.stat().st_size == 0:
            raise RuntimeError(f"Missing project README: {readme.relative_to(ROOT)}")

    print(f"PORTFOLIO BUILD PASSED — {len(PROJECTS)} approved projects; DBD excluded.")


def sync() -> None:
    if not git_is_repo():
        raise RuntimeError("This script must be run from inside a cloned Git repository.")

    status = run(["git", "status", "--short"], check=False)
    if status.stdout.strip():
        print("[warning] Working tree already has changes. They will be included in the commit.")

    run(["git", "add", "."])
    diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet"], cwd=ROOT, check=False
    )
    if diff.returncode == 0:
        print("No changes to commit.")
        return

    run(["git", "commit", "-m", "chore: rebuild portfolio from approved project set"])
    print("[ok] Local commit created.")
    print("[next] Push with your configured GitHub credentials using: git push")


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild and validate Naledi's public GitHub portfolio.")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="Belgium Campus ZIP archive")
    parser.add_argument("--sync", action="store_true", help="Commit the generated changes locally")
    args = parser.parse_args()

    try:
        source = args.source.expanduser().resolve()
        verify_source(source)
        print(f"[source] {source}")
        counts = inspect_source(source)
        write_manifest(counts)
        validate()
        if args.sync:
            sync()
        print("Done.")
        return 0
    except (OSError, zipfile.BadZipFile, FileNotFoundError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
